# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180313_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default='', help_text='\u7f16\u7801', verbose_name='\u7f16\u7801'),
        ),
    ]
