# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180314_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='url',
            field=models.CharField(default='', help_text='\u5730\u5740', max_length=100, unique=True, verbose_name='\u5730\u5740'),
        ),
    ]
